### ISSUE TITLE
Reference value problem

### ISSUE THREAD

**Issue by aadog** [uselessgoddess/defer#1]
```rust
#[test]
#[use_defer]
fn val() {
    let mut v = 0;
    defer! {
        println!("defer: {}", v)
    }
    v = 1;
    println!("home: {}", v);
}
```

**Comment by aadog** [comment]
defer:0

**Comment by aadog** [comment]
How can we make him equal to 1

**Comment by uselessgoddess** [comment]
In the current implementation, each deferred function [move](https://doc.rust-lang.org/std/keyword.move.html) (in this case `v` will be [copied](https://doc.rust-lang.org/std/marker/trait.Copy.html)) all borrowed value to self. 
This behavior may change in the future, but it will still contradict the [borrowing semantic](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html). 
[please see this example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6009f2666f6fd303c1ba1dce23ee79d8)

**Comment by uselessgoddess** [comment]
> How can we make him equal to 1

You can use unsafe pointers
```rust
#[test]
#[use_defer]
fn val() {
    let mut v = 0;
    let weak = &v as *const i32;
    defer! {
        // SAFETY: Not guaranteed, other destructors may contain ref to `v`,
        // but in this example it is safe
        println!("defer: {}", unsafe { *weak });
    }
    v = 1;
    println!("home: {}", v);
}
```

**Comment by aadog** [comment]
Thank you for your answer，The only problem with this implementation is the upval reference,The implementation of defer in Git is the best。

But usually, the correct reference of upval is necessary，In addition to the pointer, is there any other way we can simply implement it

**Comment by aadog** [comment]
It seems to be the problem of move. What can we do to make it reference by address rather than by value? Then the problem will be solved soon

**Comment by aadog** [comment]
In addition, how to install it in cargo

**Comment by uselessgoddess** [comment]
It's been a long time, I don't publish it in crates.io. 
For now, use this crate as git deps:
```toml
[dependencies]
defer = { git = "https://github.com/uselessgoddess/defer" }
```

**Comment by uselessgoddess** [comment]
> It seems to be the problem of move. What can we do to make it reference by address rather than by value? Then the problem will be solved soon

This is the rust [memory](https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html) and [thread](https://blog.rust-lang.org/2015/04/10/Fearless-Concurrency.html) safety semantics. Check my [example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f645590dcdb3a466b36136b0d8469d87)
If you don't send `v` between threads – use unsafe pointers or (non-recommended) [`Rc<RefCell<T>>`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2c4817d4992072fda0f690572bd1f3f4) or [`RefCell<T>`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c92bfa2a2dde3b22b9eb27fdcdcbbadf)

**Comment by aadog** [comment]
> 

[dependencies]
defer = { git = "https://github.com/uselessgoddess/defer" }

**Comment by aadog** [comment]
![image](https://user-images.githubusercontent.com/18098725/179389715-151b94c0-ad8f-455e-b9ca-03b4d7a5e7fd.png)

**Comment by uselessgoddess** [comment]
Sorry, my mistake. Follow the compiler's help message – write `use defer::Defer`. Later i fix bug

**Comment by uselessgoddess** [comment]
Try use 
```toml
[dependencies]
defer = { git = "https://github.com/uselessgoddess/defer", version = "0.2.0" }
```

**Comment by uselessgoddess** [comment]
> If you don't send `v` between threads – use unsafe pointers or (non-recommended) [`Rc<RefCell<T>>`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2c4817d4992072fda0f690572bd1f3f4) or [`RefCell<T>`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c92bfa2a2dde3b22b9eb27fdcdcbbadf)

Also try use less lightweight [scopeguard](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fb797b4b81e649f730882fb316476173)

**Comment by aadog** [comment]
There seems to be an even worse case where debugging isn't working properly after use_defer

**Comment by uselessgoddess** [comment]
Try enable new macro engine in CLion settings

**Comment by aadog** [comment]
It doesn't seem to work

**Comment by uselessgoddess** [comment]
Try some of these:
- update CLion or Rust plugin
- change priority of CLion system process
- force reindex your project
- disable macro engine

in CLion 2022.1.1 with Rust plugin 0.4.172 i don't have this problem
